### ISSUE TITLE
Mapping framework failed to do type cast within Map

### ISSUE THREAD

**Issue by greenlaw110** [osglworks/java-tool#77]
Java source:

```java
public class Course {
    public int id;
    public String name;
}

public class User {
    public int id;
    public String name;
    public List<Course> courses;
}
```

Yaml file:

```yaml
User(john):
  id: 3
  name: John Brad
  courses:
    - id: 3
      name: Physics
    - id: 4
      name: Science
```

After loading the yaml file, it will use `List<LinkedHashMap>` data structure for `courses`, when we use osgl-tool mapping tool to map the loaded yaml data to `User`, we expect it to be type cast from `List<LinkedHashMap>` to `List<Course>`, which is not happening.
